### ISSUE TITLE
Linear Regression Implementation: Task List

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/wildboottestjlr#6]
For the wild cluster bootstrap for linear regression models, add the following features to `boot_lm()`:

- [x] multiway clustering & subcluster bootstrapping
- [x] add control features for confidence interval inversion (maxiter & tol)
- [x] regression weights
- [x] fixed effects
- [ ] score bootstrap
- [x] Float 32 vs Float 64 option
- [ ] ...

Implemented methods: 

- [x] `boottest.lm`
- [x] `boottest.fixest` (for fixest)
- [x] `boottest.felm` (for lfe)
- [ ] `boottest.lm_robust` (for estimatr)

Supported Function Arguments from `wildboottest()`:

- [x] `predexog::AbstractVecOrMat`: exogenous predictors, including constant term, if any (X/X₁)
- [ ] ~~`predendog::AbstractVecOrMat`: endogenous predictors (Y₂) ~~
- [ ] ~~ `inst::AbstractVecOrMat`: instruments (X₂) ~~
- [ ]  ~~`H₁::Tuple{AbstractMatrix, AbstractVector}`: model constraints; same format as for H₀ ~~
- [x] `clustid::AbstractVecOrMat{<:Integer}`: data vector/matrix of error and bootstrapping cluster identifiers; see Notes 
- [x] `nbootclustvar::Integer=1`: number of bootstrap-clustering variables
- [x] `nerrclustvar::Integer=nbootclustvar`: number of error-clustering variables
- [ ] `hetrobust::Bool=true`: true unless errors are treated as iid
- [x] `feid::AbstractVector{<:Integer}`: data vector for fixed effect group identifier
- [x] `fedfadj::Bool=true`: true if small-sample adjustment should reflect number of fixed effects
- [x] `obswt`: observation weight vector; default is equal weighting
- [x] `fweights::Bool=false`: true for frequency weights
- [ ] `maxmatsize::Number`: maximum size of auxilliary weight matrix (v), in gigabytes
- [x] `ptype::PType=symmetric`: p value type (symmetric, equaltail, lower, upper)
- [ ] `bootstrapc::Bool=false`: true for bootstrap-c
- [ ] `LIML::Bool=false`: true for LIML or Fuller LIML
- [ ]  ~~`Fuller::Number`: Fuller factor ~~
- [ ]  ~~`κ::Number`: fixed κ for _k_-class estimation ~~
- [ ] ~~`ARubin::Bool=false`: true for Anderson-Rubin test ~~
- [x] `small::Bool=true`: true for small-sample corrections
- [ ] `scorebs::Bool=false`: true for score bootstrap instead of wild bootstrap
- [x] `reps::Integer=999`: number of bootstrap replications; `reps` = 0 requests classical Rao (Wald) test if `imposenull` = `true` (`false`)
- [x] `imposenull::Bool=true`: true to impose null
- [x] `auxwttype::AuxWtType=rademacher`: auxilliary weight type (rademacher, mammen, webb, normal, gamma)
- [x] `rng::AbstractRNG=MersenneTwister()`: randon number generator
- [x] `level::Number=.95`: significance level (0-1)
- [x] `rtol::Number=1e-6`: tolerance for CI bound determination
- [ ] `madjtype::MAdjType=nomadj`: multiple hypothesis adjustment (nomadj, bonferroni, sidak)
- [ ] `NH₀::Integer=1`: number of hypotheses tested, including one being tested now
- [ ]  ~~`ML::Bool=false`: true for (nonlinear) ML estimation ~~
- [ ]  ~~`scores::AbstractVecOrMat`: for ML, pre-computed scores ~~
- [ ]  ~~`β::AbstractVector`: for ML, parameter estimates ~~
- [ ]  ~~`A::AbstractMatrix`: for ML, covariance estimates ~~
- [ ] `gridmin`: vector of graph lower bounds, max length 2, `missing` entries ask wildboottest() to choose
- [ ] `gridmax`: vector of graph upper bounds
- [ ] `gridpoints`: vector of number of sampling points
- [ ] `diststat::DistStatType=nodiststat`: t to save bootstrap distribution of Wald/χ²/F/t statistics; numer to save numerators thereof
- [x] `getCI::Bool=true`: whether to return CI
- [ ] `getplot::Bool=getCI`: whether to generate plot data
- [ ] `getauxweights::Bool=false`: whether to save auxilliary weight matrix (v)
